name: Validate JSON
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ajv-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dev deps
        run: npm ci || npm i -D ajv ajv-cli

      - name: Validate Canon
        run: npx ajv -s canon/schemas/strategy_canon_v1_1.schema.json -d canon/data/exports/canon_v1_1_season1_baseline.json

      - name: Validate Rosters
        run: npx ajv -s roster_sync/schemas/roster_sync.schema.json -d roster_sync/NHL/roster_sync_nhl.json -d roster_sync/AHL/roster_sync_ahl.json

      - name: Validate Contracts
        run: npx ajv -s contracts/schemas/contracts_sync.schema.json -d contracts/contracts_sync.json
